### ISSUE TITLE
high kernel_task CPU

### ISSUE THREAD

**Issue by toonvanstrijp** [jaromeyer/XPS9570-Catalina#1]
Heey @jaromeyer, I'm trying out your repo and the boot seems smooth as the overall repo. But I'm experiencing high CPU usage by the kernel_task process. Any idea how to debug this, or what is the cause of this?

<img width="1072" alt="Screenshot 2020-03-23 at 21 33 42" src="https://user-images.githubusercontent.com/11893063/77361075-dbc1a880-6d4e-11ea-9591-9464b7087f0c.png">

**Comment by jaromeyer** [comment]
I'm pretty sure you have touchscreen enabled and like I wrote in the other issue the touchscreen runs in polling mode which results in a constant kernel_task usage of 15-30%. The guide tells you how to disable the touchscreen. After that, the kernel_task usage will only spike when touching the trackpad because it is using GPIO interrupts rather than constant polling.
Ah and maybe rebuild your kextcache once and reboot. Just to make sure everything is clean.

**Comment by jaromeyer** [comment]
@ToonvanStrijp did the audio get any better with my repo? And could you lower kernel_task usage by disabling the touchscreen?

**Comment by frbuccoliero** [comment]
I bet jaromeyer is right, my non touch 9570 has no kernel_task problem at all. This issue has been found in other EFIs too, touchscreen seems to be broken af.

**Comment by toonvanstrijp** [comment]
@jaromeyer the audio got way better! :) and using the patch to disable touchscreen fixed kernel_task usage! :)

**Comment by jaromeyer** [comment]
@ToonvanStrijp good to hear! If you keep using my repo, please report back if you face the same issue with it. Ive never had a single earrape noise since im using this setup

**Comment by hypafly** [comment]
Hello, I couldnt find the script to disable the touchscreen

I only saw this 

defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO and this for the font smoothning

**Comment by jaromeyer** [comment]
@hypafly shouldnt be required anymore to save battery
