### ISSUE TITLE
No ''Use standard function keys'' Options

### ISSUE THREAD

**Issue by qinkangdeid** [jaromeyer/XPS9570-Catalina#15]
thank you for providing a complete configuration file. with this configuration, all functions are very normal，there is only one problem，I don't see the "Use standard function keys" option in the settings.
![image](https://user-images.githubusercontent.com/17582522/81087748-a94dc280-8f2c-11ea-9b25-f1056e078058.png)

Apple ’s website describes it this way：
![image](https://user-images.githubusercontent.com/17582522/81087948-eb770400-8f2c-11ea-9433-642de61ece60.png)

https://support.apple.com/en-us/HT204436

Will there be a solution？thanks again 🙏

**Comment by frbuccoliero** [comment]
I'm not hundred percent sure but you can switch the fn-mode both in the BIOS and using Fn+Esc (you see it has a little Fn lock) this way you can switch between Media/brightness control and F1-F12 Keys as default.
Of course you can use the other one pressing Fn while using it

**Comment by jaromeyer** [comment]
this option is only available for apple keyboards. on a real mac the f keys and the fn get sent separately to the os. thats why you can then tell the os what to do if fn is pressed or not. on the xps the firmware handles the fn key and it never gets sent to the os so the os can only receive the f1-12 keys alone but not fn. that's why f1-12 are always used as f1-12 and not special functions by the os. in the bios or with fn+esc you can chose if they are default special keys, or f keys which get sent to the os and are automatically interpretet as f1-12.
