### ISSUE TITLE
OpenCore 0.6.0

### ISSUE THREAD

**Issue by BradleyHo** [jaromeyer/XPS9570-Catalina#28]
Any plans for OpenCore 0.6.0? And on another unrelated topic, how likely would you guys start a repo for Big Sur?

**Comment by frbuccoliero** [comment]
Atm i can’t test 0.6.0 since i don’t have my second machine to use for backup and to ease the process. Will try probably in few weeks. About Big Sur, the community is moving forward to be prepared for it. I personally didn’t try the betas due to my small ssd space, but i think it boots. Jaro did an awesome job with this repo. I can’t exclude some minor issues but a major OC release will surely fix all the main issues that now are giving problems to someone with the betas. Just waiting.

Francesco Buccoliero
(Very) Junior Dev
    @frbuccoliero

**Comment by jaromeyer** [comment]
Currently I don't see any reason to update to OC 0.6.0 and matching kexts for Catalina. I have been experimenting with BS about a month ago when everything was still very beta. I was able to successfully boot and run the installer. So the next update will be a completely revised EFI for Big Sur. I just dont know when. Currently working on some other projects

**Comment by frbuccoliero** [comment]
Just updated to 0.6.0 just updating the basic stuff and nothing else in the config, since they didn't add anything that needed to be tuned. All fine

PS: And of course updating the kexts.

**Comment by jaromeyer** [comment]
Sorry I'm too busy to update my repo. For now I recommend using [xxxzc's repo](https://github.com/xxxzc/xps15-9570-macos). It should even boot Big Sur, but be aware that there is a bug in the GPU driver/Whatevergreen which results in the iGPU getting stuck in higher power states.
