### ISSUE TITLE
Screen patch important for 4k models.

### ISSUE THREAD

**Issue by techsnakebo** [jaromeyer/XPS9570-Catalina#56]
Sorry where can I get info of this patch?

I have a 9570 4K running Catalina, and don't remember any 4K patch

Thank you

**Comment by ghost** [comment]
> Sorry where can I get info of this patch?
> 
> I have a 9570 4K running Catalina, and don't remember any 4K patch
> 
> Thank you

If you used this EFI folder, there is no 4K patch, you just rename the 4K config to config.plist and delete the FHD one.

**Comment by techsnakebo** [comment]
> > Sorry where can I get info of this patch?
> > I have a 9570 4K running Catalina, and don't remember any 4K patch
> > Thank you
> 
> If you used this EFI folder, there is no 4K patch, you just rename the 4K config to config.plist and delete the FHD one.

Thanks... thats why I do not remember that patch because I used the 4k plist from begining

**Comment by Fyobl** [comment]
The patch is something you apply yourself separately from the EFI you download here.

@jaromeyer can you supply a guide on how to do this as it seems lots of people are asking.

**Comment by mattclarkradio** [comment]
I am also having issues with this on my 4k 9570... I've tried applying my EDID patch but I can't seem to get it working. Big Sur is installed and boots OK, everything working well with an external 4k monitor! A guide would be amazing but understand people have jobs as well!!

**Comment by Fyobl** [comment]
Try following this guide

https://www.tonymacx86.com/threads/solved-guide-workaround-for-cdfon.306154/

**Comment by CarstenK1** [comment]
@Fyobl For me the solution does not work. I have the 4K version and System was crashing after start up with graphic error.  I added the edID to the config and the system does not crash anymore, but the built in display stays dark after half of boot. I can work only on a external display. I have the original configuration like this repo except I updated to openencore 6.3 since 6.1  didn't work for me. All Kext are like in the repo.  9570 i7 4k 32 GB

**Comment by Fyobl** [comment]
@CarstenK1 i have stayed on 0.6.1 as I have a stable build. So I wouldn’t know if anything has changed in recent updates.

You sure you have patched your EDID correctly? Have you disabled nvidia gpu?

**Comment by CarstenK1** [comment]
@Fyobl Will retry today. In fact I tried a different way for the EDID. I've bootet my catalina an got the EDID from the hackintool. From my understanding the EDID should be in every OS the same. I'will create now an USB Linux Stick to see if it's the same EDID. The config I have now, runs fine with Catalina only Big Sur have display issues. The plist shows:

I've passed now additional boot flag introduced with 0.6.3 to disable all GPU. I don't think it is the enabled GPU, since I've except the the OpenCore Version the identical config like this repo.

To be more precise: Big Sur boots and in the middle of the progressbar it seems to freeze, but only the display freezes the apple logo and progessbar is visible. If I than connect the external monitor I see the Big Sur login screen.

If I go to the display settings in Big Sur I have also two displays if external is connected. But the built in stays dark if I disconnect the external monitor.

**Comment by CarstenK1** [comment]
@Fyobl So now I exactly followed the instructions. Bootet into linux, created the file and executed the python script. Yep I got a different value that from the hackintool before. I've added it to the plist and tried again to boot Big Sur. Something changed now.... the internal display does not freeze anymore.. it turn just to black... how can I verify if nvidia gpu is disabled?

Update: tried with OpenCore 0.6.1 works also -> the difference is, that I need to disable secure boot in 0.6.1 ... 0.6.3. I don't need to disable secure boot.... but the issues regarding display is the same

**Comment by Fyobl** [comment]
@CarstenK1 im sure you have to change the EDID to hex or something before you add it to your plist.

@jaromeyer could you confirm the steps on this?

**Comment by CarstenK1** [comment]
@Fyobl it looks now like this:

`<data>00FFFFFFFFFFFF004D108D1400000000051C0104A52213780EAD8BA95335BC250C515300000001010101010101010101010101010101A6A600A0F0703E803020350058C210000018000000000000000000000000000000000000000000FE00464E564452804C513135364431000000000002410328011200000B010A20200024</data>`

This is exact the value I got from the python script

**Comment by CarstenK1** [comment]
@jaromeyer @Fyobl  I did some tests today. And it seems something is not working with the EDID at all. I replaced my system to a working Catalina Version based on this repo and for testing I added the EDID to the config. As soon I have a EDID in the config the internal screens stays black, also with Catalina. Either the process of creating the EDID is wrong or it is some other issues. And what also is confusing: In some examples I've found the data is a base64 encoded string in other examples it is a HEX value.

**Comment by CarstenK1** [comment]
Update: I tried also to use the hex EDID I got from the terminal in Catalina. I added that to the config for testing and even than Catalina stays black. How can this be? A display working and if I add the EDID of this working display it does not work on reboot anymore.

**Comment by Fyobl** [comment]
What have you got set as your boot args?

**Comment by CarstenK1** [comment]
@Fyobl Fixed it and it is working now. But need to test what was the fix. I added the EDID as base64 to the plist and I missed the latest BIOS Update, which I installed. Will remove the EDID later to see what happens.

**Comment by Fyobl** [comment]
@CarstenK1 glad you have it working.

What version BIOS was you on?

Try to leave as much information on your testing and fix so other can follow 😊

**Comment by CarstenK1** [comment]
@Fyobl I don't think it was related to the BIOS. It's about the right EDID. I couldn't find a good documentation how the EDID should look like .. is it HEX or base64... so before I installed the update (after rollback) I obtained the EDID by a script in Catalina -> https://github.com/xxxzc/xps15-9570-macos/blob/master/update.py (I just extracted the part for EDID) ...the Hex Value seems to be the same like I got from Linux.... but I used the base64 encoded...as far as I understood this was missing in the linked description above...it needs to be the base64 value.

`<key>AAPL00,override-no-connect</key>
<data>AP///////wBNEI0UAAAAAAUcAQSlIhN4Dq2LqVM1vCUMUVMAAAABAQEBAQEBAQEBAQEBAQEBpqYAoPBwPoAwIDUAWMIQAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gBGTlZEUoBMUTE1NkQxAAAAAAACQQMoARIAAAsBCiAgACQ=</data>`

I added it after update ...so I started update, after reboot it seems the progress bar freeze....just leave it on....even if the display went black...I just leave it on....at one point I restarted hard, because I thought nothing happens .....computer booted installation continued....the display went black again....and I connected the external display...and saw that I was already finished and the external displays shows the login screen... I logged in...and added the EDID to the plist...rebooted...and main display was working. Don't know if it works to put the EDID into the plist before updating.

If I remove the EDID..I get this error..:

`panic(cpu 6 caller 0xffffff800fbefa76): Kernel trap at 0xffffff7fae0e5b14, type 0=divide error, registers:
CR0: 0x000000008001003b, CR2: 0x00007fff892dde20, CR3: 0x000000001f1a0000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff93920a8400, RCX: 0x0000000000000000, RDX: 0x0000000000000000
RSP: 0xffffffc1121cbd30, RBP: 0xffffffc1121cbde0, RSI: 0x0000000000000000, RDI: 0x0000000000320032
R8:  0x0000000000000000, R9:  0x0000000000000002, R10: 0x0000000000000000, R11: 0x0000000000000780
R12: 0x0000000000000002, R13: 0x0000000000000002, R14: 0x0000000000000000, R15: 0xffffff9391842000
RFL: 0x0000000000010246, RIP: 0xffffff7fae0e5b14, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff892dde20, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 0

Backtrace (CPU 6), Frame : Return Address
0xffffffc1121cb750 : 0xffffff800fabc66d 
0xffffffc1121cb7a0 : 0xffffff800fbff073 
0xffffffc1121cb7e0 : 0xffffff800fbef6aa 
0xffffffc1121cb830 : 0xffffff800fa61a2f 
0xffffffc1121cb850 : 0xffffff800fabbf0d 
0xffffffc1121cb970 : 0xffffff800fabc1f8 
0xffffffc1121cb9e0 : 0xffffff80102bee1a 
0xffffffc1121cba50 : 0xffffff800fbefa76 
0xffffffc1121cbbd0 : 0xffffff800fbef75d 
0xffffffc1121cbc20 : 0xffffff800fa61a2f 
0xffffffc1121cbc40 : 0xffffff7fae0e5b14 
0xffffffc1121cbde0 : 0xffffff801021d5c5 
0xffffffc1121cbe50 : 0xffffff801021d4c6 
0xffffffc1121cbe80 : 0xffffff800fb01345 
0xffffffc1121cbef0 : 0xffffff800fb02254 
0xffffffc1121cbfa0 : 0xffffff800fa6113e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCFLGraphicsFramebuffer(16.0)[454E9AD8-8527-30C3-BB46-FBBA098EA330]@0xffffff7fae0aa000->0xffffff7fae167fff
            dependency: com.apple.AppleGraphicsDeviceControl(6.1.27)[7F585E8C-2D1D-358C-98A8-0F611F1FFD85]@0xffffff7fadc0e000->0xffffff7fadc11fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[65A1D60D-F9AF-37E7-B854-4127FBB3172A]@0xffffff8011ed2000->0xffffff8011ed3fff
            dependency: com.apple.iokit.IOAcceleratorFamily2(439.35.4)[BA67BC61-7BC3-3A5B-8D09-EA01DE06400C]@0xffffff7faf35b000->0xffffff7faf3c4fff
            dependency: com.apple.iokit.IOGraphicsFamily(585)[BCCD5611-3116-3255-ADBF-C5521D3B39C6]@0xffffff7faf4b3000->0xffffff7faf4e1fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[A18ACD60-A811-3624-B50D-4F929836EE79]@0xffffff8012417000->0xffffff801243efff
            dependency: com.apple.iokit.IOReportFamily(47)[0EC55CCD-966C-33F4-9B8A-1E9CB2778AE7]@0xffffff801244d000->0xffffff801244ffff

Process name corresponding to current thread: kernel_task
Boot args: darkwake=1 igfxfw=2

Mac OS version:
20B50

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x000000000f800000
KernelCache base:  0xffffff800fa00000
Kernel slide:      0x000000000f810000
Kernel text base:  0xffffff800fa10000
__HIB  text base: 0xffffff800f900000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Panic diags file available: NO (0xe00002bc)
Hibernation exit count: 0

System uptime in nanoseconds: 55775874881
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000000cfc805dfb
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000009c30d107e 0x0000000000000000
last started kext at 46261650671: @filesystems.msdosfs	1.10 (addr 0xffffff7fafe2d000, size 57344)
`
